jobs:
    build:
        docker:
            - image: cimg/rust:1.61.0
        steps:
            - checkout
            - run: cargo --version
            - run:
                name: wrapper
                command: "cargo build --release --bin beverage"
            - run:
                name: installer
                command: "cargo build --release --bin installer"