jobs:
    build:
        docker:
            - image: cimg/rust:1.61.0
        steps:
            - checkout
            - run: cargo --version
            - run:
                name: wrapper
                command: "cargo build --release"
            - run:
                name: launcher
                command: "rustc launcher.rs"