jobs:
    build:
        docker:
            - image: cimg/rust:1.61.0
        steps:
            - checkout
            - run: cargo --version
            - run:
                name: tests
                command: "HOME=/home/circleci/ cargo run"